import type { PlainData } from './plain-data.js';

export interface PopupToken<Input extends PlainData = PlainData> {
  readonly kind: 'popup';
  readonly provider: string;
  readonly name: string;
  readonly version: number;
}

export type PopupPresentation = 'default' | 'workspace';

export const UI_CONTROL_ATTRIBUTE = 'data-ss-helper-control' as const;
export const UI_CONTROL_TONE_ATTRIBUTE = 'data-ss-helper-tone' as const;
export type UiControlKind = 'button' | 'input' | 'textarea' | 'checkbox' | 'select' | 'status' | 'progress' | 'file-trigger';
export type UiControlTone = 'neutral' | 'primary' | 'danger' | 'success' | 'warning' | 'error';

export interface PopupUiContext {
  /** Re-applies Core-owned component behavior after a plugin replaces popup DOM. */
  refreshControls(root?: HTMLElement): void;
  /** Closes the current Core-owned popup without relying on its internal DOM. */
  close(): void;
}

export interface PopupRegistration<Input extends PlainData = PlainData> {
  readonly token: PopupToken<Input>;
  readonly title: string;
  readonly ariaLabel?: string;
  readonly closeLabel?: string;
  readonly presentation?: PopupPresentation;
  render(container: HTMLElement, input: Input, ui?: PopupUiContext): void | (() => void);
}

export type ToastLevel = 'info' | 'success' | 'warning' | 'error';

export interface ToastNotification {
  readonly level: ToastLevel;
  readonly message: string;
  readonly title?: string;
  readonly code?: string;
  readonly durationMs?: number;
}

export type ChatIndicatorKind = 'direct' | 'dependency';
export type ChatIndicatorState = 'hidden' | 'enabled' | 'retained';

export interface ChatIndicatorTarget {
  /** Stable opaque identity generated by Core for this workspace/chat pair. */
  readonly key: string;
  readonly workspaceId: string;
  readonly chatKey: string;
  readonly characterId?: string;
  readonly groupId?: string;
}

export interface ChatIndicatorResolution {
  readonly targetKey: string;
  readonly state: ChatIndicatorState;
  /** Dependencies actively used by this plugin for this chat. */
  readonly activeDependencies?: readonly `${string}.${string}`[];
}

export interface ChatIndicatorRegistration {
  readonly label: string;
  /** Safe Font Awesome glyph name without the `fa-` prefix. */
  readonly icon: string;
  readonly kind?: ChatIndicatorKind;
  readonly order?: number;
  resolve(targets: readonly ChatIndicatorTarget[]): readonly ChatIndicatorResolution[] | Promise<readonly ChatIndicatorResolution[]>;
  subscribe?(listener: (targetKeys?: readonly string[]) => void): () => void;
}

export interface UiPort {
  openPopup<Input extends PlainData>(token: PopupToken<Input>, input: Input): void;
  showToast(notification: ToastNotification): void;
}
